// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @title AgentPayment
 * @notice Escrow contract for AgentBill — holds OG token payments
 *         until the agent confirms job completion, then releases to agent wallet.
 * @dev Deployed on 0G Chain (chainId: 16661)
 */
contract AgentPayment {
    address public owner;

    struct Job {
        address client;
        address payable agent;
        uint256 amount;
        string invoiceId;
        string storageRootHash;   // 0G Storage proof of invoice
        JobStatus status;
        uint256 createdAt;
    }

    enum JobStatus { Pending, Paid, Released, Refunded }

    mapping(string => Job) public jobs;
    string[] public jobIds;

    event InvoiceCreated(
        string indexed invoiceId,
        address indexed client,
        address indexed agent,
        uint256 amount,
        string storageRootHash
    );
    event PaymentReceived(string indexed invoiceId, address indexed client, uint256 amount);
    event PaymentReleased(string indexed invoiceId, address indexed agent, uint256 amount);
    event PaymentRefunded(string indexed invoiceId, address indexed client, uint256 amount);

    modifier onlyOwner() {
        require(msg.sender == owner, "Not authorized");
        _;
    }

    constructor() {
        owner = msg.sender;
    }

    /**
     * @notice Register an invoice on-chain with 0G Storage proof
     * @param invoiceId Unique invoice ID (generated by agent)
     * @param agent Agent's wallet address to receive payment
     * @param storageRootHash 0G Storage root hash of the invoice PDF/JSON
     */
    function registerInvoice(
        string calldata invoiceId,
        address payable agent,
        string calldata storageRootHash
    ) external {
        require(bytes(jobs[invoiceId].invoiceId).length == 0, "Invoice exists");
        require(agent != address(0), "Invalid agent address");

        jobs[invoiceId] = Job({
            client: msg.sender,
            agent: agent,
            amount: 0,
            invoiceId: invoiceId,
            storageRootHash: storageRootHash,
            status: JobStatus.Pending,
            createdAt: block.timestamp
        });
        jobIds.push(invoiceId);

        emit InvoiceCreated(invoiceId, msg.sender, agent, 0, storageRootHash);
    }

    /**
     * @notice Pay an invoice — funds held in escrow
     */
    function pay(string calldata invoiceId) external payable {
        Job storage job = jobs[invoiceId];
        require(bytes(job.invoiceId).length > 0, "Invoice not found");
        require(job.status == JobStatus.Pending, "Already paid");
        require(msg.value > 0, "Must send OG tokens");

        job.amount = msg.value;
        job.status = JobStatus.Paid;

        emit PaymentReceived(invoiceId, msg.sender, msg.value);
    }

    /**
     * @notice Release escrow to agent after job completion
     */
    function release(string calldata invoiceId) external onlyOwner {
        Job storage job = jobs[invoiceId];
        require(job.status == JobStatus.Paid, "Not in paid state");

        uint256 amount = job.amount;
        job.status = JobStatus.Released;
        job.agent.transfer(amount);

        emit PaymentReleased(invoiceId, job.agent, amount);
    }

    /**
     * @notice Refund to client if agent fails to deliver
     */
    function refund(string calldata invoiceId) external onlyOwner {
        Job storage job = jobs[invoiceId];
        require(job.status == JobStatus.Paid, "Not in paid state");

        uint256 amount = job.amount;
        job.status = JobStatus.Refunded;
        payable(job.client).transfer(amount);

        emit PaymentRefunded(invoiceId, job.client, amount);
    }

    function getJob(string calldata invoiceId) external view returns (Job memory) {
        return jobs[invoiceId];
    }

    function getJobCount() external view returns (uint256) {
        return jobIds.length;
    }
}
